---
services:
  versity:
    container_name: versity
    image: ghcr.io/versity/versitygw:v1.3.1@sha256:f50499999ef31ac7b5af12ff1becf1a8c20dc6a0b1b632d2a2dbffa9037f7c69
    user: 1000:1000
    environment:
      ROOT_ACCESS_KEY: 'versity'
      ROOT_SECRET_KEY: $VERSITY_ROOT_SECRET_KEY
      VGW_BACKEND: 'posix'
      VGW_BACKEND_ARGS: '/data/buckets --chuid true --chgid true'
      VGW_IAM_DIR: '/data/accounts'
      LOGFILE: '/log/access.log'
    networks:
      - caddy
    volumes:
      - /mnt/tank/docker/versity:/data
      - /mnt/flash/docker/versity/log:/log
    restart: always
    labels:
      caddy_0: versity.serek.xyz
      caddy_0.reverse_proxy: "{{upstreams 7070}}"
      caddy_0.import: cf

networks:
  caddy:
    external: true
