---
# yaml-language-server: $schema=https://schemas.serek.xyz/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mc-vanilla
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.3
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://schemas.serek.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mc-vanilla
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    extraEnv:
      PAPER_CHANNEL: experimental
      TZ: America/New_York
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java25@sha256:d118097b6df85143c190396131b73a2dc20382d913c04aaee39fc1b06ce93c7f
    livenessProbe:
      initialDelaySeconds: 30
    minecraftServer:
      difficulty: normal
      eula: true
      gameMode: survival
      jvmXXOpts: "--add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"
      memory: 6144M
      motd: "Vanilla for you."
      onlineMode: true
      ops: "UnworldlyAlex"
      overrideServerProperties: true
      pvp: true
      rcon:
        enabled: true
      spawnProtection: 0
      type: PAPER
      version: "26.2"
      viewDistance: 12
      whitelist: "UnworldlyAlex,The_Windmill,RedMoonCactus,BonezTheMiner,homernays"
      worldSaveName: vanilla
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    podSecurityContext:
      fsGroup: 3000
      runAsGroup: 3000
      runAsUser: 3000
    readinessProbe:
      initialDelaySeconds: 30
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 200m
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: vanilla.serek.xyz
    startupProbe:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: mc-vanilla-secret
      targetPath: minecraftServer.rcon.password
      valuesKey: RCON_PASSWORD
