#cloud-config
ssh_pwauth: false

groups:
 - botadmin

users:
  - name: aster
    groups: botadmin
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: alex
    groups: botadmin
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOFyVit0RfzUzV3uSA9yAo9QIomZKx+hKhxX/vfIrZ7q

runcmd:
 - echo 'This instance was provisioned by Terraform.' >> /etc/tf-provisioned.txt
