#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy_lightstream
- name: get latest release of a public repository
  local_action: community.general.github_release
  become: false
  args:
    user: benbjohnson
    repo: litestream
    action: latest_release
  register: latest_release

- name: install the lightstream rpm from latest release
  ansible.builtin.dnf:
    name: "https://github.com/benbjohnson/litestream/releases/download/{{ latest_release.tag }}/litestream-{{ latest_release.tag[1:] }}-linux-arm64.rpm"
    state: present
    disable_gpg_check: true
  notify: restart lightstream service

- name: deploy configuration file
  ansible.builtin.copy:
    src: files/litestream.yml
    dest: /etc/litestream.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart lightstream service

- # present due to dnf install
  name: start and enable lightstream service
  ansible.builtin.systemd_service:
    name: litestream
    enabled: true
    state: started
